### ISSUE TITLE
Mugs dissapeared after server restart

### ISSUE THREAD

**Issue by LucasJohansson** [FlodGamedev/OceanCraftBugtracker#10]
When restarting the server during a multiplayer session,

I expect all mugs on tables etc to stay in the world,

But they all dissapeared! Along with all the water inside them ;-)

**Comment by FlodGamedev** [comment]
Hey LucasJohansson - thanks for reporting - we have fixed that bug aside with all on the grill did disappear, too - in the upcomming version.
