### ISSUE TITLE
Not being able to build (under sails?)

### ISSUE THREAD

**Issue by LucasJohansson** [FlodGamedev/OceanCraftBugtracker#11]
(15th April 2021)
When trying to place wall in a area that looks clear of objects,

I expect to be able to build walls etc,

But I could not place them there!

This area affected was looking a bit like this:

![image](https://user-images.githubusercontent.com/16883017/108327034-39fb4380-71cb-11eb-8007-82ffd8a5327e.png)

Even after removing sails though, we could still not build there.

**Comment by FlodGamedev** [comment]
wow... you are right - we found the bug and solved it in our version!
at the end it was something else - but you lead us to the right point!
