### ISSUE TITLE
Ceiling death bug

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#12]
Ceiling death bug
when you die under a ceiling your medkit will be teleported to the ceiling, instead of on your body. 
1)  play normal 
2) build a ceiling above you
3) when you die your medkit will be teleported above you
https://youtu.be/6Z2IXxrt9FY (did this with Imback)

**Comment by FlodGamedev** [comment]
thanks for the bug - have fixed it! now spawns on head instead of one meter above head
