### ISSUE TITLE
Duplication bug

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#13]
Items can be duplicated
1) place an item (bell pepper, pumpkin, etc) into the water
2) Hook it with a grappling hook and as its traveling to you.
3) Your item will be in your inventory from the hook, but randomly there is a chance that another will be there as well. 
Here is the gameplay I did while playing. https://youtu.be/Yj3XcJoh07U

**Comment by BuzzTheAmbassador** [comment]
(done with imback)

**Comment by FlodGamedev** [comment]
thanks for the vieeo - please give me a hint - when in the video this happens...

**Comment by imbackgaming** [comment]
https://youtu.be/w1S4Ol3ChR8 Here is a shorter video of the bug 👍

**Comment by FlodGamedev** [comment]
this is the fishing bug - not the duplication

**Comment by imbackgaming** [comment]
I sent the wrong link my bad sorry to waste your time this is the correct link https://youtu.be/3THXN_odH3s

**Comment by FlodGamedev** [comment]
O - M - G - that one took me a while... but we solved it! thanks at the BUG-BUSTERS! We fixed it in the upcoming version!
