### ISSUE TITLE
Fish Stacking Bug

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#14]
Glitch found 
1) person throws fishing rod into water like normal catches fish
2) press small button on side to pull in at once
3) throw back in water and you can catch another
4) you can have multiple fish on the hook, and keep fishing even if you didn't grab the fish off of the hook. (done with imback as well)

**Comment by FlodGamedev** [comment]
thanks for the report - we did fix that one in our version.
