### ISSUE TITLE
Inventory dragging bug

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#15]
In the inventory, when dragging items with your thumbstick, if you close it when you are in the motion of having the item in your trigger, and then open it back up, the item will stay in the position it was dragged into, not going back to it's original spot.
Reproduction steps: 
1) get an item
2) press trigger and drag the item to wherever you want on your inventory (outside of it, etc)
3) close your inventory while still having the item in your trigger hand.
4) re-opening the inventory, you will see the item is in the position the place where you left it with the trigger.

**Comment by BuzzTheAmbassador** [comment]
video: https://www.youtube.com/watch?v=MnLf17FLH-A

**Comment by FlodGamedev** [comment]
thanks for the bug - we fixed it in our version!
