### ISSUE TITLE
Left Hand Placing bug

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#16]
You cannot place or turn objects with your left thumbstick.
1) get a placeable build (water filters, beds, etc)
2) try to turn them with the thumbstick or place them with your trigger.
3) it wont work.

**Comment by BuzzTheAmbassador** [comment]
video: https://www.youtube.com/watch?v=MnLf17FLH-A

**Comment by FlodGamedev** [comment]
thanks for the bug - we fixed it in our version!
