### ISSUE TITLE
Multiple fish on 1 hook

### ISSUE THREAD

**Issue by imbackgaming** [FlodGamedev/OceanCraftBugtracker#18]
This bug allows players to have multiple fishes on 1 hook 
1) play as normal build a fishing rod
2) catch a fish but press the grab button 
3) throw back in water and you can catch another on the same hook 

https://youtu.be/w1S4Ol3ChR8
My suggested fix is take away the ability to press the grab button to reel In instantly once a fish is caught

**Comment by FlodGamedev** [comment]
thanks for reporting! we discovered the bug and solved in our version1
