### ISSUE TITLE
Fishing rod's cousin also having a seizure

### ISSUE THREAD

**Issue by TheDunedinChad** [FlodGamedev/OceanCraftBugtracker#20]
Hello Hello! 

I was playing OceanCraft with friend, MysticMiles#2095 and when he made a fishing rod and stuck it out, it went balistic and kept on swerving around like a racecar that has lost its front tire but luckely when he restarted his game, it fixed it.

Anyway just wanted to tell you that, you dont have to fix it, it only happenes on small occasions

From Ed (or Lyk1e#4666 on discord)

**Comment by FlodGamedev** [comment]
thanks for reporting - the rod is a complete new one and is already released.
