### ISSUE TITLE
2 bugs

### ISSUE THREAD

**Issue by JokerLocki** [FlodGamedev/OceanCraftBugtracker#22]
I was playing on my raft. I was going to break water boiler to place it in other place. Wood in the boiler renewed. I repeted this a few times and wood was going to respawn.

Was playing on my friends raft and his corn has gliched out. he was able to control it without touching it and on diffrent heights.

PS: Second bug seems working only on the host.           

Version 0.3.10

**Comment by FlodGamedev** [comment]
thanks for reporting. please try to describe the bugs and how to reproduce
them

JokerLocki ***@***.***> schrieb am Sa. 20. März 2021 um 22:35:
