### ISSUE TITLE
Water boiling (again)

### ISSUE THREAD

**Issue by JokerLocki** [FlodGamedev/OceanCraftBugtracker#23]
When joining a world there is a chance that water purifiers will duplicate. Its only a visual glitch coz they dont work but they still have some physics, so for some people when you place something on the duplicate they will see it floating.

PS: Im Capselek#4042 and again was playing with R3tr0Dud3#6345

Version 0.3.10

**Comment by FlodGamedev** [comment]
thanks for reporting - this issue was fixed in the upcoming version 0.4.1
