### ISSUE TITLE
Game was jittery when "joining" old game

### ISSUE THREAD

**Issue by Loothin** [FlodGamedev/OceanCraftBugtracker#25]
Been playing for a couple of days, really enjoy it. Each time I get back into the game my son hosts there are a few more issues:

Son hosted game - ran great for him. No jittery behavior

For me:

Yesterday was unable to see any plants growing in old plant boxes or if they were watered (could see the plant in a plant box I created just fine). Only issue yesterday

Today had several issues joining the same board we had been working on:
1. Still had plant issue
2. Son's character was jumping all around
3. Stuff in water was jumping back and forth
4. Balloons were no longer moving in the air (just static - son could see them just fine)
5. I *think* fish were also not moving though only fished once and forgot to check closer (shark was still moving)
6. Towards the end the fishing pole got equipped in my hand and I could no longer remove it (couldn't switch to nothing or slingshot or anything, also couldn't bring up inventory in that hand any longer)

Last thing to mention is that I left the game to the menu and went back in and it was working fine for maybe 5 or 10 seconds and then issues started back up. I then later quit the game and reopened it, joined the board again and same thing. Looked great for 5 or 10 seconds then issues started again (minus plants, could never see the plants in the old planter boxes even when rejoining)

Here is a video I recorded showing some of the issues. Let me know if you have any questions. (We love the game though)

https://photos.app.goo.gl/ZYjwxjW33vF55kWR9[Video from today](https://photos.app.goo.gl/ZYjwxjW33vF55kWR9)  

Version 0.3.10

**Comment by Loothin** [comment]
Sent the following to Flod on discord as well:

Ok, issues remained no matter what I tried tonight. Here is all I did:
1. Started the game as usual, my son hosting from Quest 2 on USA East and me joining on Quest 2
2. Switched to Canada East 
3. Redeemed code on Steam and joined via Quest 2 over Virtual Desktop (still on Canada East)
4. I switched to Quest 1 and back to USA East
5. Still on Quest 1 but USA West

In each of these scenarios the game would look great (minus the old planter boxes not working for me) but would then get jittery after 5 to 10 seconds. It always looked great to my son on his headset. He did not have any of the issues. He can still see the plants and everything runs smooth.

One thing I did not mention before with the plants is that I can still plant something and water it in the old planters and my son will see it and the wetness of the soil but I never see the plant or wetness even if I was the one to plant it.

**Comment by FlodGamedev** [comment]
thanks for reporting this bug - we are currently investigating this

**Comment by FlodGamedev** [comment]
hey ho - version 0.4.x is on the way - we changed the network code a lot - please give us feedback if this did solve your problems.

**Comment by Loothin** [comment]
Awesome, it will be a few days but I will definitely check. We are just in
the middle of a 21 hr drive

**Comment by FlodGamedev** [comment]
assuming it's fixed now
