### ISSUE TITLE
I copied someone's island

### ISSUE THREAD

**Issue by DefaultyXD** [FlodGamedev/OceanCraftBugtracker#26]
A couple of minutes ago i played Oceancraft Vr, fist i joined my island and made it public so others could join. when i joined, there where no items in my chest, and my watermugs where gone and my farm whas empty. Then, someone joined my island, we where talking a bit and then i told me that i could visit his island. I walked around on his island for a bit, because it whas prety big. Then i decided to go back to my island, so i went back to the main menu. When i got there, i went to host game, and started up my island, again as public, and was planning to improve my island. but when i joined my world, it whas a bit strange... the island i just been to had been copied over to my world. my own island whas gone, and it had been replaced by the other island. there whas no stuff in the chests, and i did not have stuff in my inv. the only items on the island where 1 raw fish that the guy put on the grill, and a pumpkin, that also laid at the same spot as the other island. So basically, i just ctrl c, ctrl v'd the island i been to.

**Comment by FlodGamedev** [comment]
thanks for reporting - we found that bug and it will be fixed in the next version!
