### ISSUE TITLE
Duplication Glitch 

### ISSUE THREAD

**Issue by PeakAxis** [FlodGamedev/OceanCraftBugtracker#27]
Version 0.3.x Update
Multiplayer coop
After playing the Game for an hour I encountered a bug that did not take the object away when placed allowing for an infinite supply. This would apply to any placeable structure in the game. 
This was first noticed 1h10 mins during our playthrough after I had placed ladder, only one ladder was in the inventory so should have disappeared when placed. After that, any other structure created turned out to have the same effect. 

When reloading the game, this no longer became an issue.

**Comment by FlodGamedev** [comment]
thanks for reporting - we'll investigate this bug!

**Comment by FlodGamedev** [comment]
Thanks for posting - the bug is fixed in the upcomming version 0.4.1
