### ISSUE TITLE
app lab version lagging when building

### ISSUE THREAD

**Issue by skulkiller9000** [FlodGamedev/OceanCraftBugtracker#31]
After the latest update (0.6) playing the app lab version on meta quest 2 has been awful. the new features are great, but every time someone holds a buildable out the game lags for everyone. It makes it extremely hard to build and especially hard to play multiplayer.

**Comment by ClodeFlodlab** [comment]
Hi. We fixed this issue with the current patch (0.6.17). Everything runs smooth again now.
