### ISSUE TITLE
Fire not putting out

### ISSUE THREAD

**Issue by VrBoi27** [FlodGamedev/OceanCraftBugtracker#32]
When I try to put fire out with water I pour in directly in the middle and for some reason it won’t go out I do this multiple times and it ends up burning my oceancraft now when I pour water if the fire spreads it puts out the surrounding pallets with fire but not where it originally started it makes it very difficult to play the game when you can’t even put out the fire

**Comment by ClodeFlodlab** [comment]
We optimized the mug in the current update (0.6.17). Please check out, if you are now able to put out the fire. If you still have the problem, feel free to reopen the issue.
