### ISSUE TITLE
Cant drink water

### ISSUE THREAD

**Issue by VrBoi27** [FlodGamedev/OceanCraftBugtracker#33]
Water in this game is insanely difficult to drink and barely works and when I attempt to drink it usually just pours to the ground if you could maybe make a button in your inventory when you put the mug in their wear you just hit drink and you drink it that would be helpful but the physical drinking is very difficult and I die so often due to it

**Comment by ClodeFlodlab** [comment]
We optimized the mug in the current update (0.6.17). Please check out, if you are now able to drink. If you still have the problem, feel free to reopen the issue.
