### ISSUE TITLE
Able to jump in the water to refill hunger & thirst.

### ISSUE THREAD

**Issue by Sirvoid** [FlodGamedev/OceanCraftBugtracker#35]
We can jump in the water by moving in our playspace and doing so make us respawn instantly and refill the hunger and the thirst to half.

V0.6.17, Playing on Quest 1

**Comment by styledev** [comment]
To note this can only be done with smooth move.

**Comment by ClodeFlodlab** [comment]
Hello,
Thank you very much for the bug report. We fixed this issue in Update 0.7x - Islands
