### ISSUE TITLE
Crafting

### ISSUE THREAD

**Issue by Cheeser27** [FlodGamedev/OceanCraftBugtracker#37]
Tools and Deco are not available in the crafting menu on the meta quest 2 platform (possibly others, but I only have it on quest). Maybe I'm just an idiot and I'm not playing the game right, but I'm not going to be able to play the game to it's potential if I can't shoot drops or fish for food.

**Comment by Cheeser27** [comment]
Forgot to add that the food category doesnt appear

**Comment by ClodeFlodlab** [comment]
Hi. 
We changed the crafting system to crafting tables in the last update. If you look into your book, you can find a "choppingblock". Once you crafted it, you can use it to craft the other items.
