### ISSUE TITLE
The cup placing on the water filters is a bit awkward, because it has to be in some sort of specific way. 

### ISSUE THREAD

**Issue by BuzzTheAmbassador** [FlodGamedev/OceanCraftBugtracker#4]
read title^

**Comment by FlodGamedev** [comment]
please help us by describing the steps needed to reproduce the bugs and by describing the intended behavior from your point of view

**Comment by BuzzTheAmbassador** [comment]
hey flod! 

This bug kind of happens at random times, when you place a cup, whether it'd be directly into the center of the hologram of the cup, or not, sometimes it would just not go off and produce water. The intended behavior should be...well... that it produces water.

**Comment by FlodGamedev** [comment]
we changed the detection of the cup in the future version of the game.
