### ISSUE TITLE
Tides Moving

### ISSUE THREAD

**Issue by Cheeser27** [FlodGamedev/OceanCraftBugtracker#40]
I am not sure if this is an actual game function, but sometimes the tides will randomly change direction or position, making it impossible to hook in new items which can be fairly annoying. I noticed that this happened after I placed a sail, though I do not know if they are correlated with each other, but regardless, this is a game breaking issue for me and my friends.

**Comment by ClodeFlodlab** [comment]
Hi
As you guessed the direction change correlates with the sail. (Basically everytime one of you changes the sial direction, the wind direction changes)
We optimised how the sail works in the new Update 0.7x - Islands. We hope it is now more intuitive and less confusing.
