### ISSUE TITLE
Plants not showing

### ISSUE THREAD

**Issue by LudoFriend** [FlodGamedev/OceanCraftBugtracker#41]
When I plant vegetables the other players cannot see them growing in the soil. They can only see the vegetables once I have picked them.

**Comment by LudoFriend** [comment]
Also the plants are gone when I next log on

**Comment by ClodeFlodlab** [comment]
Hello,
we had an issue with the savesystem of build objects (which includes the plants). This should be fixed in the new Update 0.7x - Islands.
