### ISSUE TITLE
Irem Duplication

### ISSUE THREAD

**Issue by Bman61700** [FlodGamedev/OceanCraftBugtracker#44]
im on the latest version and sometimes when i go to pick items up from a crate it will add the item im holding when I move forward, it doesn't take the items out of my crate either it will keep adding it in my hand until i stop moving forward or drop the stacked items. Im pretty sure this happened when I had picked up an item and started moving forward as soon as I picked it up. Sometimes it will take the items from the crate but sometimes it will not.

**Comment by Nucleo59** [comment]
During our games, we encountered problems with inventory storage. Objects disappear when we transfer an entire item to storage chests.

**Comment by ClodeFlodlab** [comment]
Hello,
We could replicate a bug, where teleporting and grabbing items out of the crate at the same time led to duplication. We fixed this in the new Update 0.7x - Islands.
If you still find problems with the crate, please feel free to open this issue again.
