### ISSUE TITLE
The Fishing rod having a seizure

### ISSUE THREAD

**Issue by TheDunedinChad** [FlodGamedev/OceanCraftBugtracker#5]
Hello My discord name is Lyk1e#4666 and i have noticed 2 glitches
1. Sometimes when i switch to my grappel hook i cant switch back to my hand and i am just stuck there basically doing nothing.
2. Sometimes when i pull out my rod it starts having a seizure and spinning everywhere. even when i build a new one it still spins like crazy.

**Comment by FlodGamedev** [comment]
can you help me making this reproduceable? as soon as i know how to reproduce i can fix

**Comment by TheDunedinChad** [comment]
Dear FlodGameDev

it was a 1 timer thing and when i made another fishing rod, it stil flinged

From Ed

**Comment by FlodGamedev** [comment]
we are reworking the fishing rod physic from ground up. closing as no longer relevant.
