### ISSUE TITLE
items reset

### ISSUE THREAD

**Issue by coolguye6** [FlodGamedev/OceanCraftBugtracker#6]
i got on a raft i was working on and all of my inventory items got deleted but the weird thing is that my inventory also got reset to the inventory you start out with

**Comment by FlodGamedev** [comment]
Thank you for reporting that bug - the inventory is saved per player NAME at the moment - did you rename yourself?

We will fix this behaviour in the future.

Please tell me if this was the cause of the problem

**Comment by b00stJuNKy** [comment]
Similar issue, lost everything in the chests and pots but kept my inventory and raft. Applab 0.3.10 no name change
