### ISSUE TITLE
Players hands can bug out and disappear.

### ISSUE THREAD

**Issue by Cyclonejack88** [FlodGamedev/OceanCraftBugtracker#7]
During a session with Flod I noticed a bug, When Flod exited the game all of the items he had spawned in despawned when he disconnected. I happened to be holding a cup he spawned in my left hand when he disconnected, the cup despawned when he left and as I was holding it in my left hand, my left hand despawned along with it and I was left with only a right hand until I exited the game.

**Comment by FlodGamedev** [comment]
Hey Jack - does this happen only when an admin has magically spawned items? or does this happen with every inventory item an other player has given you - and then leaves the game?

**Comment by FlodGamedev** [comment]
hey jack thanks for reporting - we solved it in our version!
