### ISSUE TITLE
World Kept Spawning in without any resources in the ocean

### ISSUE THREAD

**Issue by WAVESSSS** [FlodGamedev/OceanCraftBugtracker#8]
While Me and My Friends Were Going to play on our World We started yesterday, We went to go collect wood and there was nothing in the Ocean but water

**Comment by FlodGamedev** [comment]
Thanks for reporting the bug.

The spawnrate of stuff in the ocean is influenced by the speed of your boat.

The only thing that affects this at the moment is the sail - so if you have build and placed a sail - and rotated it. this could have stopped your sail.

Destroying the sail does not restart your boat. 

Instead you have to rebuild a sail and put it in the wind again.

Please tell me if this solved your problem!

**Comment by WAVESSSS** [comment]
it solved my problem thx
