### ISSUE TITLE
Caught fish is stuck up in the air

### ISSUE THREAD

**Issue by LucasJohansson** [FlodGamedev/OceanCraftBugtracker#9]
During a multiplayer session (on 14th Feb 2021), the host kept having problems with fishing. His fish would get stuck like this:

![image](https://user-images.githubusercontent.com/16883017/108324951-d708ad00-71c8-11eb-9653-580d661a5b17.png)

The only way to get the fish to his inventory was to place down the controller, and walk to the end of the line (since he has a pretty small room this was difficult!).

Playing the next day, this issue was gone, and we could not re-produce this issue.

**Comment by LucasJohansson** [comment]
PS. Fishing rod look the upside down all the time.

**Comment by imbackgaming** [comment]
The bug I posted a couple mins ago causes this to happen

**Comment by FlodGamedev** [comment]
thanks for reporting - the bug has been found and fixed - release in the next verson.
